#! /bin/bash

for arg; do
    for remote in $(git remote); do
        echo "deleting  $remote/$arg"
        git push $remote :"$arg" 2>/dev/null
    done
    echo "deleting  local $arg"
    git branch -D "$arg" 2>/dev/null
done
