#!/bin/bash

set -e

currentBranch=$(git branch --show-current);
git fetch;
for arg; do
	git checkout "$arg";
	git rebase origin/master;
done;

git push --force-with-lease origin "$@";
	
git checkout $currentBranch;
