#! /bin/bash
version="$1";
if [ $version ]; then
apt install "php$version-"{mysql,mbstring,cli,bcmath,cgi,curl,fpm,gmp,json,opcache,xml,zip,sqlite3,gd,intl} -y
else echo 'You need to specify a php version!' >&2;
exit 1;
fi
