#!/bin/bash

inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

base=${2:-master}

if [ "$1" == "n" ]; then
      github_path="compare/${base}...$(git rev-parse --abbrev-ref HEAD)"
 else github_path="pulls"
fi

if [ $inside_git_repo ]; then
 
remove_at_git_from_url="$(sed s-git@-https://- <<< $(git remote get-url origin))"

git_url_without_dot_git=$(sed s/\\.git// <<< $remove_at_git_from_url)

replace_second_colon=$(sed s-:-/-2 <<< $git_url_without_dot_git)

exec google-chrome  "${replace_second_colon}/${github_path}" > /dev/null 2>&1

else

  echo "This is not a git repository"

fi
